gallery/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'registration/logged_out.html'}),
    url(r'^register/$', views.register, name='register'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.AlbumDateDetailView.as_view(month_format='%m'), name='gallery-detail'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', views.AlbumDayArchiveView.as_view(month_format='%m'), name='gallery-archive-day'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', views.AlbumMonthArchiveView.as_view(month_format='%m'), name='gallery-archive-month'),
    url(r'^album/(?P<year>\d{4})/$', views.AlbumYearArchiveView.as_view(), name='pl-gallery-archive-year'),
    url(r'^album/$', views.AlbumArchiveIndexView.as_view(), name='pl-gallery-archive'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumDetailView.as_view(), name='pl-gallery'),
    url(r'^albumlist/$', views.AlbumListView.as_view(), name='album-list'), 
    url(r'^album/new/$', views.album_new, name='album_new'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album_update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album_delete'),
    
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.PhotoDateDetailView.as_view(month_format='%m'), name='photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', views.PhotoDayArchiveView.as_view(month_format='%m'), name='photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', views.PhotoMonthArchiveView.as_view(month_format='%m'), name='photo-archive-month'),
    url(r'^photo/(?P<year>\d{4})/$', views.PhotoYearArchiveView.as_view(), name='pl-photo-archive-year'),
    url(r'^photo/$', views.PhotoArchiveIndexView.as_view(), name='pl-photo-archive'),
    url(r'^photo/(?P<pk>[0-9]+)/$', views.PhotoDetailView.as_view(), name='pl-photo'),
    url(r'^photolist/$', views.PhotoListView.as_view(), name='photo-list'),
    url(r'^photo/new/$', views.PhotoAdd.as_view(), name='photo_new'),
    url(r'^photo/change/(?P<pk>[0-9]+)/$', views.PhotoUpdate.as_view(), name='photo_change'),
    url(r'^photo/delete/(?P<pk>[0-9]+)/$', views.PhotoDelete.as_view(), name='photo_delete'),

    # Deprecated URLs.
    url(r'^album/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.AlbumDateDetailOldView.as_view(), name='pl-gallery-detail'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', views.AlbumDayArchiveOldView.as_view(), name='pl-gallery-archive-day'),
    url(r'^album/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', views.AlbumMonthArchiveOldView.as_view(), name='pl-gallery-archive-month'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<pk>[0-9]+)/$', views.PhotoDateDetailOldView.as_view(), name='pl-photo-detail'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', views.PhotoDayArchiveOldView.as_view(), name='pl-photo-archive-day'),
    url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', views.PhotoMonthArchiveOldView.as_view(), name='pl-photo-archive-month')
]

www/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

app_name = 'gallery'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('gallery.urls', namespace='gallery')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.urlresolvers import reverse
from django.conf import settings
from .managers import AlbumQuerySet, PhotoQuerySet

LATEST_LIMIT = getattr(settings, 'GALLERY_ALBUM_LATEST_LIMIT', None)
SAMPLE_SIZE = getattr(settings, 'GALLERY_ALBUM_SAMPLE_SIZE', 5)


class Album(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200, blank=False, verbose_name='Названия')
    description = models.TextField(verbose_name='Описания')
    created_d = models.DateTimeField(default=now)
    mod_d = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_public = models.BooleanField(default=True)
    objects = AlbumQuerySet.as_manager()

    class Meta:
        ordering = ["mod_d"]

    def __str__(self):
        return "Альбом: %s, User: %s" % (self.title, self.user)
   
    def get_absolute_url(self):
        return reverse('gallery:pl-gallery', kwargs={'pk': self.pk})
 

class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=200, blank=False)
    image = models.ImageField(upload_to='mediafiles')
    created_d = models.DateTimeField(default=now)
    mod_d = models.DateTimeField(auto_now_add=False, auto_now=True)
    description = models.CharField(max_length=200, blank=True)
    is_public = models.BooleanField(default=True)
    objects = PhotoQuerySet.as_manager()

    class Meta:
        ordering = ["mod_d"]
  
    def __str__(self):
        return "%s, %s" % (self.title, self.album)
 
    def save(self, *args, **kwargs):
        if self.pk is None:
            self.pk = self.id
        super(Photo, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('gallery:pl-photo', args=[self.id])

    def public_albums(self):
        """Return the public galleries to which this photo belongs."""
        return self.albums.filter(is_public=True)

gallery/forms.py
from django import forms
from .models import Album, Photo


class AlbumForm(forms.ModelForm):
    class Meta: 
        model = Album
        fields = ['user', 'title', 'description']
        

class PhotoForm(forms.ModelForm):
    class Meta: 
        model = Photo
        fields = ['album', 'image', 'title', 'description']

gallery/views.py
import warnings

from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Album, Photo
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import AlbumForm, PhotoForm




class PhotoAdd(CreateView):
    model = Photo
    fields = ['album', 'image', 'title', 'description']

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['album', 'image', 'title', 'description']
    template_name = 'photo_update_form.html'

class PhotoDelete(DeleteView):
    model = Photo
    success_url = reverse_lazy('gallery:index')


@login_required
def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.author = request.user
            album.save()
            return redirect('album-detail', pk=album.pk)
    else:
        form = AlbumForm()
    return render(request, 'gallery/gallery_edit.html', {'form': form})


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['user', 'title', 'description']
    template_name_suffix = '_update_form'  

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('index')


def index(request):
    context = {
        'title': 'Home page title!!!'
    }
    return render(request, 'gallery/index.html', context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login/')
    else:
        form = UserCreationForm()

        args = {'form': form}
        return render(request, 'registration/reg_form.html', args)





class AlbumListView(ListView):
    queryset = Album.objects.filter(is_public=True)
    paginate_by = 20


class AlbumDetailView(DetailView):
    queryset = Album.objects.filter(is_public=True)


class AlbumDateView(object):
    queryset = Album.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_empty = True


class AlbumDateDetailView(AlbumDateView, DateDetailView):
    pass


class AlbumArchiveIndexView(AlbumDateView, ArchiveIndexView):
    pass


class AlbumDayArchiveView(AlbumDateView, DayArchiveView):
    pass


class AlbumMonthArchiveView(AlbumDateView, MonthArchiveView):
    pass


class AlbumYearArchiveView(AlbumDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.filter(is_public=True)
    paginate_by = 20


class PhotoDetailView(DetailView):
    queryset = Photo.objects.filter(is_public=True)


class PhotoDateView(object):
    queryset = Photo.objects.filter(is_public=True)
    date_field = 'created_d'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True


# Deprecated views.

class DeprecatedMonthMixin(object):

    """Representation of months in urls has changed from a alpha representation ('jan' for January)
    to a numeric representation ('01' for January).
    Properly deprecate the previous urls."""

    query_string = True

    month_names = {'jan': '01',
                   'feb': '02',
                   'mar': '03',
                   'apr': '04',
                   'may': '05',
                   'jun': '06',
                   'jul': '07',
                   'aug': '08',
                   'sep': '09',
                   'oct': '10',
                   'nov': '11',
                   'dec': '12', }

    def get_redirect_url(self, *args, **kwargs):
        print('a')
        warnings.warn(
            DeprecationWarning('Months are now represented in urls by numbers rather than by '
                               'their first 3 letters. The old style will be removed in Photologue 3.4.'))


class AlbumDateDetailOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(AlbumDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:album-detail', kwargs={'year': kwargs['year'],
                                                            'month': self.month_names[kwargs['month']],
                                                            'day': kwargs['day']})


class AlbumDayArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(AlbumDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:album-archive-day', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']],
                                                                 'day': kwargs['day']})


class AlbumMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(AlbumMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:album-archive-month', kwargs={'year': kwargs['year'],
                                                                   'month': self.month_names[kwargs['month']]})


class PhotoDateDetailOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:photo-detail', kwargs={'year': kwargs['year'],
                                                          'month': self.month_names[kwargs['month']],
                                                          'day': kwargs['day']})


class PhotoDayArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:photo-archive-day', kwargs={'year': kwargs['year'],
                                                               'month': self.month_names[kwargs['month']],
                                                               'day': kwargs['day']})


class PhotoMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('gallery:photo-archive-month', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']]})

gallery/templates/gallery/album_archive.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Новые альбомы{% endblock %}

{% block content %}


  <div class="container">
      <div id="page_content">
          <div class="row col-lg-12">
              {% if user.is_authenticated %}
              <div style="float:right;"><a href="{% url 'gallery:album_new' %}" class="btn btn-default">Создать альбом</a></div>
              <h1 class="page-header">Новые альбомы</h1> 
              {% else %}
              <h1 class="page-header">Новые альбомы</h1>
              {% endif %}
          </div>
	  <div class="row">
	      <aside class="col-md-2">
		  <h4>Фильтр по годам</h4>
		  <ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
		  </ul>
              </aside>
              <main class="col-md-10">		      	
			{% if latest %}
			    {% for album in latest %}
			    	{% include "gallery/includes/gallery_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>Не найдено по запросу фотографии</p>
			{% endif %}	
	      </main>
	  </div>
      </div>
  </div>
	
{% endblock %}

gallery/templates/gallery/album_archive_day.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Альбомы {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Альбомы {{ show_day }} года{% endblocktrans %}</h1>
    </div>

    <div class="row col-lg-12">
        {% if object_list %}
            {% for album in object_list %}
                {% include "gallery/includes/gallery_sample.html" %}
            {% endfor %}
        {% else %}
            <p>Не найдено по запросу</p>
        {% endif %}
    </div>
    
    <div><a href="{% url 'gallery:gallery-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">Все альбомы за месяц</a></div>

{% endblock %}

gallery/templates/gallery/album_archive_year.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Альбомы {{ show_year }} года{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>Фильтр по месяцам</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'gallery:gallery-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				{% for gallery in object_list %}
			        {% include "gallery/includes/gallery_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>Не найдено по запросу фотографии</p>
			{% endif %}

		    <div><a href="{% url 'gallery:pl-gallery-archive' %}" class="btn btn-default">Все альбомы</a></div>

		</main>

	</div>

{% endblock %}

gallery/templates/gallery/album_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ album.title }}{% endblock %}

{% block content %}

<div class="row col-lg-12">
        <h1 class="page-header">{{ album.title }}</h1>
        <p class="muted"><small>Создано {{ album.created_d }}</small></p>        
        {% if album.description %}{{ album.description|safe }}{% endif %}
	    
		<div class="row col-lg-12">
		   {% for photo in photos %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
		        </a>
		   {% endfor %}
		</div>
	
<br>
<br>
<br>
        <div>
            {% if user.is_authenticated %}
	    	<a href="{% url 'gallery:album-list' %}" class="btn btn-default">Все альбомы</a>  
 	    	<a href="{% url 'gallery:album_update' album.id %}" class="btn btn-default">Изменить</a>
	    	<a href="{% url 'gallery:album_delete' album.id %}" class="btn btn-default">Удалить</a>
            {% else %}
            	<a href="{% url 'gallery:album-list' %}" class="btn btn-default">Все альбомы</a> 
            {% endif %}
 	</div>
</div>

{% endblock %}

gallery/templates/gallery/album_list.html
{% extends "gallery/root.html" %}
{% load i18n %}

{% block title %}{% trans "All galleries" %}{% endblock %}

{% block content %}
<div class="container">
    <div class="row col-lg-12">
        {% if user.is_authenticated %}
        <div style="float:right;"><a href="{% url 'gallery:album_new' %}" class="btn btn-default">{% trans "Создать альбом" %}</a></div>
        <h1 class="page-header">{% trans "Все альбомы" %}</h1>
        {% else %}
        <h1 class="page-header">{% trans "Все альбомы" %}</h1>
        {% endif %}
    </div>

    {% if object_list %}
        {% for album in object_list %}
            <div class="row col-lg-12">
                <h2><a href="{{ album.get_absolute_url }}">{{ album.title }}</a></h2>
                <p class="muted"><small>{% trans "Создано" %} {{ album.created_d }}</small></p>
                {% if album.description %}<p>{{ album.description|safe }}</p>{% endif %}
                {% for photo in album.sample %}
                    <a href="{{ photo.get_absolute_url }}">
                         <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <div class="row col-lg-12">{% trans "No galleries were found" %}.</div>
    {% endif %}

    {% include "gallery/includes/paginator.html" %}
  </div>  
{% endblock %}

gallery/templates/gallery/gallery_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Вы точно хотите удалить "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock %}

gallery/templates/gallery/gallery_update_form.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

gallery/templates/gallery/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
	<h1>Добро пожаловать</h1>
	<p>
	    Вы можете войти в свой аккаунт!
	</p>
	<h2>Авторизация</h2>
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <button type="submit">Войти</button>
	</form>
    </div>

{% endblock %}

gallery/templates/gallery/navbar.html
{% extends "base.html" %}
{% load staticfiles %}

{% block navbar %}
<nav class="container navbar navbar-default" role="navigation">
      <div class="navbar-header ">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Photologue Demo</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li class="galleries dropdown">
              <a data-target="#" href="" class="dropdown-toggle" data-toggle="dropdown">
                Gallery views<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="sub-page"><a href="/photologue/gallery/">Date views</a></li>
                <li class="sub-page"><a href="/photologue/gallerylist/">List views</a></li>
              </ul>
            </li>
            <li class="photos dropdown">
              <a data-target="#" href="" class="dropdown-toggle" data-toggle="dropdown">
                Photo views<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="sub-page"><a href="/photologue/photo/">Date views</a></li>
                <li class="sub-page"><a href="/photologue/photolist/">List views</a></li>
              </ul>
            </li>
            <li><a href="/news/">News</a></li>
          </ul>
        </div>
</nav>
{% endblock %}

{% block content %}{% endblock %}

gallery/templates/gallery/photo_archive.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photos" %}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row col-lg-12">
        {% if user.is_authenticated %}
        <div style="float:right;"><a href="{% url 'gallery:photo_new' %}" class="btn btn-default">Добавить фото</a></div>
        <h1 class="page-header">Новые фотографии</h1>
        {% else %}
        <h1 class="page-header">Новые фотографии</h1>
        {% endif %}
    </div>

	<div class="row">
		
		<aside class="col-md-2">

			<h4>Сортировка по годам</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:pl-photo-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for photo in latest %}
			        <a href="{{ photo.get_absolute_url }}">
			             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
			        </a>
			    {% endfor %}
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %} 
			

		</main>

	</div>
</div>

{% endblock %}



gallery/templates/gallery/photo_archive_year.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Фотографии {{ show_year }} года{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>Фильтр по месяцам</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'gallery:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				<div class="row col-lg-12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.image.url }}" width="140" height="100" class="thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
				</div>
			{% else %}
				<p>No photos were found</p>
			{% endif %}

		    <div><a href="{% url 'gallery:pl-photo-archive' %}" class="btn btn-default">Все фотографии</a></div>

		</main>

	</div>

{% endblock %}





gallery/templates/gallery/photo_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Вы точно хотите удалить "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock %}

gallery/templates/gallery/photo_edit.html
{% extends 'base.html' %}

{% block content %}
   <h1>Добавить новое фото</h1>
   <form method="POST" class="post-form">{% csrf_token %}
       {{ form.as_p }}
       <button type="submit" class="save btn btn-default">Сохранить</button>
   </form>
{% endblock %}

gallery/templates/gallery/root.html
{% extends "base.html" %}